/**
 * POSP Category Brokerage Seed Data
 * 245 products (144 GI + 75 LI + 26 HI) from Trustner's actual insurer commission grids
 */

export interface SeedProduct {
  lob: 'GI' | 'LI' | 'HI';
  productLine: string;
  productName: string;
  insurer: string;
  trustnerCommission: number;
  basis: string;
}

// --- TIER SHARING MATRIX (10 categories × 3 tiers = 30 configs) ---
export const TIER_SHARING_SEED: Array<{ category: string; tier: string; sharingPercent: number }> = [
  { category: 'A', tier: 'HIGH', sharingPercent: 65 },
  { category: 'A', tier: 'MEDIUM', sharingPercent: 55 },
  { category: 'A', tier: 'LOW', sharingPercent: 40 },
  { category: 'B', tier: 'HIGH', sharingPercent: 70 },
  { category: 'B', tier: 'MEDIUM', sharingPercent: 60 },
  { category: 'B', tier: 'LOW', sharingPercent: 45 },
  { category: 'C', tier: 'HIGH', sharingPercent: 75 },
  { category: 'C', tier: 'MEDIUM', sharingPercent: 65 },
  { category: 'C', tier: 'LOW', sharingPercent: 50 },
  { category: 'D', tier: 'HIGH', sharingPercent: 80 },
  { category: 'D', tier: 'MEDIUM', sharingPercent: 70 },
  { category: 'D', tier: 'LOW', sharingPercent: 55 },
  { category: 'D_PLUS', tier: 'HIGH', sharingPercent: 82 },
  { category: 'D_PLUS', tier: 'MEDIUM', sharingPercent: 72 },
  { category: 'D_PLUS', tier: 'LOW', sharingPercent: 57 },
  { category: 'E', tier: 'HIGH', sharingPercent: 82 },
  { category: 'E', tier: 'MEDIUM', sharingPercent: 72 },
  { category: 'E', tier: 'LOW', sharingPercent: 57 },
  { category: 'E_PLUS', tier: 'HIGH', sharingPercent: 85 },
  { category: 'E_PLUS', tier: 'MEDIUM', sharingPercent: 75 },
  { category: 'E_PLUS', tier: 'LOW', sharingPercent: 60 },
  { category: 'F1', tier: 'HIGH', sharingPercent: 85 },
  { category: 'F1', tier: 'MEDIUM', sharingPercent: 75 },
  { category: 'F1', tier: 'LOW', sharingPercent: 60 },
  { category: 'F2', tier: 'HIGH', sharingPercent: 88 },
  { category: 'F2', tier: 'MEDIUM', sharingPercent: 78 },
  { category: 'F2', tier: 'LOW', sharingPercent: 62 },
  { category: 'F3', tier: 'HIGH', sharingPercent: 90 },
  { category: 'F3', tier: 'MEDIUM', sharingPercent: 80 },
  { category: 'F3', tier: 'LOW', sharingPercent: 65 },
];

// --- ALL 245 PRODUCTS ---
export const PRODUCT_CATALOG_SEED: SeedProduct[] = [
  // ===========================================================================
  // GENERAL INSURANCE (144 products)
  // ===========================================================================

  // --- Motor - Two Wheeler (40 products) ---
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Comprehensive (Scooter) - Metro', insurer: 'ICICI Lombard', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Comprehensive (Scooter) - Non-Metro', insurer: 'ICICI Lombard', trustnerCommission: 20, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Comprehensive (Bike) - Metro', insurer: 'ICICI Lombard', trustnerCommission: 15, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Comprehensive (Bike) - Non-Metro', insurer: 'ICICI Lombard', trustnerCommission: 10, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW SATP (Standalone TP)', insurer: 'ICICI Lombard', trustnerCommission: 2.5, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW SAOD (Standalone OD)', insurer: 'ICICI Lombard', trustnerCommission: 20, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter Fresh (1+5) - West Metro', insurer: 'Bajaj Allianz', trustnerCommission: 57.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter Fresh (1+5) - West Non-Metro', insurer: 'Bajaj Allianz', trustnerCommission: 50, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter Fresh (1+5) - North', insurer: 'Bajaj Allianz', trustnerCommission: 50, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter Fresh (1+5) - South', insurer: 'Bajaj Allianz', trustnerCommission: 40, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter Fresh (1+5) - East', insurer: 'Bajaj Allianz', trustnerCommission: 45, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter Comp (Old)', insurer: 'Bajaj Allianz', trustnerCommission: 50, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW SA OD', insurer: 'Bajaj Allianz', trustnerCommission: 45, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW New (1+5) Scooter - Metro', insurer: 'HDFC ERGO', trustnerCommission: 40, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW New (1+5) Scooter - Non-Metro', insurer: 'HDFC ERGO', trustnerCommission: 35, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW New (1+5) Bike - Metro', insurer: 'HDFC ERGO', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW New (1+5) Bike - Non-Metro', insurer: 'HDFC ERGO', trustnerCommission: 15, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Old Scooter Comp', insurer: 'HDFC ERGO', trustnerCommission: 40, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Old Bike Comp', insurer: 'HDFC ERGO', trustnerCommission: 20, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter SAOD', insurer: 'HDFC ERGO', trustnerCommission: 30, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter AOTP', insurer: 'HDFC ERGO', trustnerCommission: 45, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW EV (All OEM)', insurer: 'HDFC ERGO', trustnerCommission: 30, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bundle (New Scooty) - East', insurer: 'TATA AIG', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bundle (New Scooty) - West', insurer: 'TATA AIG', trustnerCommission: 40, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bundle (New Bike) - East', insurer: 'TATA AIG', trustnerCommission: 45, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bundle (New Bike) - West', insurer: 'TATA AIG', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Rollover PKG', insurer: 'TATA AIG', trustnerCommission: 32.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW STP Rollover', insurer: 'TATA AIG', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Comprehensive (Scooter)', insurer: 'SBI General', trustnerCommission: 26, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Comprehensive (Bike <=600CC)', insurer: 'SBI General', trustnerCommission: 15, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW SATP (Scooter)', insurer: 'SBI General', trustnerCommission: 15, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW SATP - Bike', insurer: 'Reliance General', trustnerCommission: 51.5, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW SATP - Scooter', insurer: 'Reliance General', trustnerCommission: 57.5, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Fresh (1+5) Scooter - East', insurer: 'Cholamandalam', trustnerCommission: 40, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Scooter Cat 0', insurer: 'Kotak Zurich', trustnerCommission: 42, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bike Cat 0', insurer: 'Kotak Zurich', trustnerCommission: 30, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bundled New', insurer: 'Oriental', trustnerCommission: 23, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Package', insurer: 'Oriental', trustnerCommission: 16.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bundled (1+5) New', insurer: 'National', trustnerCommission: 21, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Two Wheeler', productName: 'TW Bundle/Package', insurer: 'United India', trustnerCommission: 17, basis: 'Net Premium' },

  // --- Motor - Private Car (31 products) ---
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp (Petrol) - Metro', insurer: 'ICICI Lombard', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp (Petrol) - Non-Metro', insurer: 'ICICI Lombard', trustnerCommission: 20, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp (Diesel) - Metro', insurer: 'ICICI Lombard', trustnerCommission: 15, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp (Diesel) - Non-Metro', insurer: 'ICICI Lombard', trustnerCommission: 10, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD', insurer: 'ICICI Lombard', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SATP', insurer: 'ICICI Lombard', trustnerCommission: 2.5, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp Petrol - Metro', insurer: 'Bajaj Allianz', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp Petrol - Non-Metro', insurer: 'Bajaj Allianz', trustnerCommission: 15, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp Diesel - All', insurer: 'Bajaj Allianz', trustnerCommission: 10, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD', insurer: 'Bajaj Allianz', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD - Petrol NCB (<10K OD)', insurer: 'HDFC ERGO', trustnerCommission: 17.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD - Petrol NCB (10-50K OD)', insurer: 'HDFC ERGO', trustnerCommission: 19.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD - Petrol NCB (50K-1L OD)', insurer: 'HDFC ERGO', trustnerCommission: 21, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD - Petrol NCB (1L-2L OD)', insurer: 'HDFC ERGO', trustnerCommission: 23, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD - Petrol NCB (>2L OD)', insurer: 'HDFC ERGO', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR SAOD - Diesel', insurer: 'HDFC ERGO', trustnerCommission: 15, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp Petrol - Metro', insurer: 'TATA AIG', trustnerCommission: 25, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp Petrol - Non-Metro', insurer: 'TATA AIG', trustnerCommission: 17.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Comp Diesel', insurer: 'TATA AIG', trustnerCommission: 10, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Bundle (1+3) Honda/Hyundai/KIA', insurer: 'TATA AIG', trustnerCommission: 30, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR NewComp - Platinum (Kolkata)', insurer: 'SBI General', trustnerCommission: 60, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR NewComp - Silver (Kolkata)', insurer: 'SBI General', trustnerCommission: 57, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Non-New Comp - Platinum', insurer: 'SBI General', trustnerCommission: 49.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Non-New Comp - Silver', insurer: 'SBI General', trustnerCommission: 46.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Petrol Comp - NCB', insurer: 'Cholamandalam', trustnerCommission: 22, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR New Petrol Preferred RTO', insurer: 'Kotak Zurich', trustnerCommission: 22.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Petrol NCB (1+1)', insurer: 'Kotak Zurich', trustnerCommission: 20.5, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Bundled New', insurer: 'Oriental', trustnerCommission: 26, basis: 'OD Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Bundled (1+3) New', insurer: 'National', trustnerCommission: 10, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Bundle (1+3)', insurer: 'United India', trustnerCommission: 15, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Private Car', productName: 'PVT CAR Petrol Comp', insurer: 'Reliance General', trustnerCommission: 20, basis: 'OD Premium' },

  // --- Motor - Commercial Vehicle (60 products) ---
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 3W - Comp', insurer: 'ICICI Lombard', trustnerCommission: 40, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 3W - SATP', insurer: 'ICICI Lombard', trustnerCommission: 40, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV upto 2.5T - Comp', insurer: 'ICICI Lombard', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV upto 2.5T - SATP', insurer: 'ICICI Lombard', trustnerCommission: 35, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 2.5T-3.5T - Comp', insurer: 'ICICI Lombard', trustnerCommission: 40, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 2.5T-3.5T - SATP', insurer: 'ICICI Lombard', trustnerCommission: 40, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 7.5T-15T - Comp', insurer: 'ICICI Lombard', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 15T-20T - Comp', insurer: 'ICICI Lombard', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 20T-43T - Comp', insurer: 'ICICI Lombard', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV >43T - Comp', insurer: 'ICICI Lombard', trustnerCommission: 20, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Tractor - Comp (Fresh)', insurer: 'ICICI Lombard', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Tractor - SATP', insurer: 'ICICI Lombard', trustnerCommission: 25, basis: 'TP Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV 3W - Comp', insurer: 'ICICI Lombard', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV Taxi - Comp', insurer: 'ICICI Lombard', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV School Bus', insurer: 'ICICI Lombard', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV <2K Comp - West Metro', insurer: 'Bajaj Allianz', trustnerCommission: 66, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV <2K Comp - East', insurer: 'Bajaj Allianz', trustnerCommission: 55, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 2.5-3.5K - Comp', insurer: 'Bajaj Allianz', trustnerCommission: 42.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 12K+ HCV - Comp', insurer: 'Bajaj Allianz', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV 3W - Comp', insurer: 'Bajaj Allianz', trustnerCommission: 15, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'School Bus', insurer: 'Bajaj Allianz', trustnerCommission: 71, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Tractor Fresh - Comp', insurer: 'Bajaj Allianz', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV upto 2.5T - Comp', insurer: 'New India / Chola', trustnerCommission: 45, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 2.5-3.5T - Comp', insurer: 'New India / Chola', trustnerCommission: 45, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 3.5-7.5T - Comp', insurer: 'New India / Chola', trustnerCommission: 17.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 7.5-12T - Comp', insurer: 'New India / Chola', trustnerCommission: 22.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 12-20T - Comp', insurer: 'New India / Chola', trustnerCommission: 22.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 20-40T - Comp', insurer: 'New India / Chola', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 40-43T - Comp', insurer: 'New India / Chola', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV >43T - Comp', insurer: 'New India / Chola', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV 3W Auto - Comp', insurer: 'New India / Chola', trustnerCommission: 17.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'School Bus', insurer: 'New India / Chola', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Staff Bus', insurer: 'New India / Chola', trustnerCommission: 42, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Tractor New - Comp', insurer: 'New India / Chola', trustnerCommission: 45, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Tractor Renewal - Comp', insurer: 'New India / Chola', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Excavator/Earth Mover', insurer: 'New India / Chola', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Harvester', insurer: 'New India / Chola', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV upto 2.5T - Comp', insurer: 'HDFC ERGO', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 2.5-3.5T - Comp', insurer: 'HDFC ERGO', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'CV Comp - Various', insurer: 'HDFC ERGO', trustnerCommission: 22.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV LCV - Comp', insurer: 'TATA AIG', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV HCV - Comp', insurer: 'TATA AIG', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV 3W - Comp', insurer: 'TATA AIG', trustnerCommission: 67.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV 4W School Bus', insurer: 'TATA AIG', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV Taxi - Comp', insurer: 'TATA AIG', trustnerCommission: 45, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Tractor - Comp', insurer: 'TATA AIG', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV upto 2.5T - Platinum', insurer: 'SBI General', trustnerCommission: 42.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 2.5-3.5T - Platinum', insurer: 'SBI General', trustnerCommission: 26, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV Tractor - Platinum', insurer: 'SBI General', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'Agri Tractor - Platinum', insurer: 'SBI General', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCCV LCV Payout', insurer: 'Shriram GI', trustnerCommission: 40, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV <=2000 Kg', insurer: 'United India', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 2000-3500 Kg', insurer: 'United India', trustnerCommission: 38, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'School Bus', insurer: 'United India', trustnerCommission: 52, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCCV up to 2.5T', insurer: 'Oriental', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'School Bus 3W PCCV', insurer: 'Oriental', trustnerCommission: 37.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'PCV School Bus', insurer: 'Kotak Zurich', trustnerCommission: 58, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV 0-2500 Ton', insurer: 'Kotak Zurich', trustnerCommission: 40, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'School Bus', insurer: 'Reliance General', trustnerCommission: 55, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Motor - Commercial Vehicle', productName: 'GCV <2K WB Kolkata', insurer: 'Reliance General', trustnerCommission: 48, basis: 'Net Premium' },

  // --- Non-Motor (13 products) ---
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Fire & Engineering (<1 Lakh)', insurer: 'TATA AIG', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Fire & Engineering (1-5 Lakh)', insurer: 'TATA AIG', trustnerCommission: 27.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Fire & Engineering (>5 Lakh)', insurer: 'TATA AIG', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'GPA (<5 Lakh)', insurer: 'TATA AIG', trustnerCommission: 10, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'GPA (5-15 Lakh)', insurer: 'TATA AIG', trustnerCommission: 12.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'GPA (>15 Lakh)', insurer: 'TATA AIG', trustnerCommission: 15, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Marine (<2 Lakh)', insurer: 'TATA AIG', trustnerCommission: 22.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Marine (>2 Lakh)', insurer: 'TATA AIG', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Liability/WC (<5 Lakh)', insurer: 'TATA AIG', trustnerCommission: 25, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Liability/WC (>5 Lakh)', insurer: 'TATA AIG', trustnerCommission: 27.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Co-operative', insurer: 'TATA AIG', trustnerCommission: 35, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'PCI Comprehensive (New/Renewal)', insurer: 'Reliance General', trustnerCommission: 22.5, basis: 'Net Premium' },
  { lob: 'GI', productLine: 'Non-Motor', productName: 'Extended Warranty', insurer: 'Reliance General', trustnerCommission: 20, basis: 'Net Premium' },

  // ===========================================================================
  // LIFE INSURANCE (75 products)
  // ===========================================================================

  // --- Shriram Life (9 products) ---
  { lob: 'LI', productLine: 'Traditional', productName: 'Assured Income Plan (15/15 PPT)', insurer: 'Shriram Life', trustnerCommission: 71, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Assured Income Plan (12/12 PPT)', insurer: 'Shriram Life', trustnerCommission: 65, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Assured Income Plan (10/10 PPT)', insurer: 'Shriram Life', trustnerCommission: 55, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Assured Savings POS (15/15 PPT)', insurer: 'Shriram Life', trustnerCommission: 60, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Assured Savings POS (15/10 PPT)', insurer: 'Shriram Life', trustnerCommission: 45, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Premier Assured Benefit (20/10 PPT)', insurer: 'Shriram Life', trustnerCommission: 58, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Early Cash Plan (20/10 PPT)', insurer: 'Shriram Life', trustnerCommission: 67, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Sunishchit Labh (20 PPT)', insurer: 'Shriram Life', trustnerCommission: 78, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Super Income Plan (10-15 PPT)', insurer: 'Shriram Life', trustnerCommission: 73, basis: '1st Year Premium' },

  // --- Bajaj Life (12 products) ---
  { lob: 'LI', productLine: 'PAR', productName: 'PAR All Products (5 PPT)', insurer: 'Bajaj Life', trustnerCommission: 34, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR', productName: 'PAR All Products (7 PPT)', insurer: 'Bajaj Life', trustnerCommission: 44, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR', productName: 'PAR All Products (>=10 PPT)', insurer: 'Bajaj Life', trustnerCommission: 54, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Non-PAR', productName: 'Non-PAR All (5 PPT)', insurer: 'Bajaj Life', trustnerCommission: 39, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Non-PAR', productName: 'Non-PAR All (7 PPT)', insurer: 'Bajaj Life', trustnerCommission: 49, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Non-PAR', productName: 'Non-PAR All (>=10 PPT)', insurer: 'Bajaj Life', trustnerCommission: 54, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Annuity', productName: 'Annuity All (5 PPT)', insurer: 'Bajaj Life', trustnerCommission: 29, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Annuity', productName: 'Annuity All (>=10 PPT)', insurer: 'Bajaj Life', trustnerCommission: 44, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'Term (<10 PPT)', insurer: 'Bajaj Life', trustnerCommission: 54, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'Term (>=10 PPT)', insurer: 'Bajaj Life', trustnerCommission: 59, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'TULIP IPG', insurer: 'Bajaj Life', trustnerCommission: 19, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'ULIP SWG', insurer: 'Bajaj Life', trustnerCommission: 9, basis: '1st Year Premium' },

  // --- ICICI Prudential (7 products) ---
  { lob: 'LI', productLine: 'PAR/Non-PAR', productName: 'Par/Non-Par (5 PPT) Offline', insurer: 'ICICI Prudential', trustnerCommission: 32.5, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR/Non-PAR', productName: 'Par/Non-Par (7 PPT) Offline', insurer: 'ICICI Prudential', trustnerCommission: 41.5, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR/Non-PAR', productName: 'Par/Non-Par (10 PPT) Offline', insurer: 'ICICI Prudential', trustnerCommission: 55, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR/Non-PAR', productName: 'Par/Non-Par (12+ PPT) Offline', insurer: 'ICICI Prudential', trustnerCommission: 64, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Protection', productName: 'Protection (5-12+ PPT) Offline', insurer: 'ICICI Prudential', trustnerCommission: 52.5, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Pension', productName: 'Gold Pension Savings (10 PPT)', insurer: 'ICICI Prudential', trustnerCommission: 30, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Smart Goal Assure (7+ PPT)', insurer: 'ICICI Prudential', trustnerCommission: 25, basis: '1st Year Premium' },

  // --- Bandhan Life (10 products) ---
  { lob: 'LI', productLine: 'Term', productName: 'iTerm Prime / Comfort', insurer: 'Bandhan Life', trustnerCommission: 50, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'iTerm Prime ROP (10 PPT)', insurer: 'Bandhan Life', trustnerCommission: 55, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'iTerm Prime ROP (15 PPT)', insurer: 'Bandhan Life', trustnerCommission: 60, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'iIncome Wealth (7 PPT)', insurer: 'Bandhan Life', trustnerCommission: 38, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'iIncome Wealth (10 PPT)', insurer: 'Bandhan Life', trustnerCommission: 66, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'iIncome Wealth (12 PPT)', insurer: 'Bandhan Life', trustnerCommission: 68, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'iGVishwas (10 PPT)', insurer: 'Bandhan Life', trustnerCommission: 65, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'iGVishwas (12 PPT)', insurer: 'Bandhan Life', trustnerCommission: 68, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'iInvest II (<10 PPT)', insurer: 'Bandhan Life', trustnerCommission: 17, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'iInvest II (>=10 PPT)', insurer: 'Bandhan Life', trustnerCommission: 20, basis: '1st Year Premium' },

  // --- TATA AIA Life (11 products) ---
  { lob: 'LI', productLine: 'PAR', productName: 'Shubh Maha Life Gold (5 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 40, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR', productName: 'Shubh Maha Life Gold (10 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 54, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR', productName: 'Shubh Flexi (12+ PPT)', insurer: 'TATA AIA Life', trustnerCommission: 62, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'PAR', productName: 'SVIP (10 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 57, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Protection', productName: 'Shubh Shakti (5-11 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 57, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Protection', productName: 'Shubh Shakti (12+ PPT)', insurer: 'TATA AIA Life', trustnerCommission: 62, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Non-PAR', productName: 'Fortune Guarantee Plus (5 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 52, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Non-PAR', productName: 'Fortune Guarantee Plus (12 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 62, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Non-PAR', productName: 'Fortune Guarantee Pension (12 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 62, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'Pro-Fit NROP (5-9 PPT)', insurer: 'TATA AIA Life', trustnerCommission: 40.7, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'Pro-Fit WL (10+ PPT)', insurer: 'TATA AIA Life', trustnerCommission: 55.1, basis: '1st Year Premium' },

  // --- SUD Life (9 products) ---
  { lob: 'LI', productLine: 'Traditional', productName: 'Century Royale (12 PPT)', insurer: 'SUD Life', trustnerCommission: 80, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Century Income (12 PPT)', insurer: 'SUD Life', trustnerCommission: 75, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Smart Income (12 PPT)', insurer: 'SUD Life', trustnerCommission: 70, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Century Royale (10 PPT)', insurer: 'SUD Life', trustnerCommission: 70, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Century Gold (10 PPT)', insurer: 'SUD Life', trustnerCommission: 70, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'Smart Term (RP)', insurer: 'SUD Life', trustnerCommission: 70, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Guarantee Royale (10 PPT)', insurer: 'SUD Life', trustnerCommission: 50, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'POS Sanchay (10 PPT)', insurer: 'SUD Life', trustnerCommission: 60, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'Life Star TULIP (10 PPT)', insurer: 'SUD Life', trustnerCommission: 10, basis: '1st Year Premium' },

  // --- Go Digit Life (6 products) ---
  { lob: 'LI', productLine: 'Traditional', productName: 'Digit Icon (5 PPT)', insurer: 'Go Digit Life', trustnerCommission: 25, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Digit Icon (7 PPT)', insurer: 'Go Digit Life', trustnerCommission: 45, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Digit Icon (10 PPT)', insurer: 'Go Digit Life', trustnerCommission: 70, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Traditional', productName: 'Digit Icon (12-15 PPT)', insurer: 'Go Digit Life', trustnerCommission: 75, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'Glow (Regular Pay)', insurer: 'Go Digit Life', trustnerCommission: 50, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'Glow Plus (Regular Pay)', insurer: 'Go Digit Life', trustnerCommission: 60, basis: '1st Year Premium' },

  // --- LIC (11 products) ---
  { lob: 'LI', productLine: 'Endowment', productName: 'New Endowment (15+ PPT)', insurer: 'LIC', trustnerCommission: 20, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Endowment', productName: 'New Endowment (10-14 PPT)', insurer: 'LIC', trustnerCommission: 15, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Endowment', productName: 'Jeevan Lakshya (15+ PPT)', insurer: 'LIC', trustnerCommission: 20, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Whole Life', productName: 'Jeevan Anand (15+ PPT)', insurer: 'LIC', trustnerCommission: 20, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Whole Life', productName: 'Jeevan Utsav (15+ PPT)', insurer: 'LIC', trustnerCommission: 25, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Money Back', productName: 'New Money Back (20/15 PPT)', insurer: 'LIC', trustnerCommission: 15, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'Saral Jeevan (15+ PPT)', insurer: 'LIC', trustnerCommission: 12.5, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Term', productName: 'Yuva Term (15+ PPT)', insurer: 'LIC', trustnerCommission: 20, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'SIIP (AP 75K+)', insurer: 'LIC', trustnerCommission: 4, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'ULIP', productName: 'Index Plus (AP 1.2L+)', insurer: 'LIC', trustnerCommission: 5.75, basis: '1st Year Premium' },
  { lob: 'LI', productLine: 'Annuity', productName: 'All Annuity (Single Prem)', insurer: 'LIC', trustnerCommission: 2, basis: 'Single Premium' },

  // ===========================================================================
  // HEALTH INSURANCE (26 products)
  // ===========================================================================

  // --- SBI General Health (12 products) ---
  { lob: 'HI', productLine: 'Indemnity', productName: 'Alpha (SI 5L-9L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Alpha (SI 10L-14L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Alpha (SI >15L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Super Health (SI 5L-9L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Super Health (SI >10L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Supreme (SI 5L-9L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Supreme (SI >10L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Super Top Up (SI >15L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'IPA (SI 10L-14L) - New', insurer: 'SBI General', trustnerCommission: 50, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Renewal', productName: 'All Health Products - Renewal', insurer: 'SBI General', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Renewal', productName: 'Portability - Super Health/Supreme >10L', insurer: 'SBI General', trustnerCommission: 30, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Group', productName: 'GMC (Group Mediclaim)', insurer: 'SBI General', trustnerCommission: 7.5, basis: 'Net Premium' },

  // --- Aditya Birla Health (6 products) ---
  { lob: 'HI', productLine: 'Indemnity', productName: 'Max Plus (SI >=10L) - Fresh', insurer: 'Aditya Birla Health', trustnerCommission: 45, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Other Indemnity (SI >=10L) - Fresh', insurer: 'Aditya Birla Health', trustnerCommission: 42.5, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Indemnity', productName: 'Any (SI <10L) - Fresh', insurer: 'Aditya Birla Health', trustnerCommission: 15, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Renewal', productName: 'All Products - Renewal', insurer: 'Aditya Birla Health', trustnerCommission: 20, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Renewal', productName: 'Renewal (Member age 60+)', insurer: 'Aditya Birla Health', trustnerCommission: 10, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Fixed Benefit', productName: 'Health Meter (Cap)', insurer: 'Aditya Birla Health', trustnerCommission: 12.5, basis: 'Net Premium' },

  // --- Special Referral Arrangement (8 products) ---
  { lob: 'HI', productLine: 'Special', productName: 'HI New Biz Single Year (3.8x)', insurer: 'Care/Cigna/Niva/SBI/Rel/HDFC/TATA', trustnerCommission: 49, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Special', productName: 'HI New Biz Multi Year (3.4x)', insurer: 'Care/Cigna/Niva/Rel/Chola/TATA', trustnerCommission: 44, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Special', productName: 'Travel Insurance (2.8x)', insurer: 'Care/Reliance/TATA AIG', trustnerCommission: 36, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Special', productName: 'PA Personal Accident (3.4x)', insurer: 'Reliance/TATA AIG/SBI', trustnerCommission: 44, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Special', productName: 'HI Porting (2.0x)', insurer: 'Care/Cigna/Niva Bupa', trustnerCommission: 26, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Special', productName: 'Renewal >80% Persistency (1.8x)', insurer: 'Care/Cigna/Niva/SBI/Rel/HDFC/TATA', trustnerCommission: 23, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Special', productName: 'Renewal <80% Persistency (1.6x)', insurer: 'Care/Cigna/Niva/SBI/Rel/HDFC/TATA', trustnerCommission: 21, basis: 'Net Premium' },
  { lob: 'HI', productLine: 'Special', productName: 'Age 60+ Fresh/Porting (flat)', insurer: 'All HI Insurers', trustnerCommission: 8, basis: 'Net Premium' },
];
